# Generated by Django 5.1.7 on 2025-03-23 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_course_priority_course_rd_color_manualsession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='course',
            name='rd_color',
        ),
        migrations.AddField(
            model_name='course',
            name='card_color',
            field=models.CharField(default='#378006', help_text='Couleur de la carte pour ce cours', max_length=20),
        ),
    ]
